# Generated by Django 4.2.18 on 2025-03-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('nickname', models.CharField(blank=True, max_length=50)),
                ('rating', models.FloatField(default=0.0)),
                ('role', models.IntegerField(default=0)),
                ('club', models.IntegerField(default=0)),
                ('slug', models.SlugField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
    ]
